KingShipper/Areas/Admin/Controllers/UserBusinessController.cs
using KingShipper.Library;
using KingShipper.Models;
using Microsoft.Security.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingShipper.Entity;
using KingShipper.Service.Services;
using System.Web.Helpers;

namespace KingShipper.Areas.Admin.Controllers
{
    public class UserBusinessController : Controller
    {
        HttpClient client;
        public UserBusinessController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }
        // GET: Admin/UserBusiness
        [HttpGet]
        public async Task<ActionResult> Index(int userId)
        {
            string url = Config.WebApiUrl + "/api/UserBusiness/GetAll?userId=" + userId;
            TempData["UserRoleID"] = userId;
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<UserBusiness>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<UserBusiness>>().Result;
            }
            return this.View(responseData);
        }

        [HttpPost]
        public async Task<ActionResult> Update(string businessId)
        {
            int userId = int.Parse(TempData["UserRoleID"].ToString());
            var userBusiness = UserBusinessService.GetUserBusinessById(userId, businessId);
            if (userBusiness.Status == null || userBusiness.Status == 0)
            {
                userBusiness.Status = 1;
            }
            else
            {
                userBusiness.Status = 0;
            }
            string url = Config.WebApiUrl + "/api/UserBusiness/Update";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, userBusiness);
            var responseData = new ResponseModel<UserBusiness>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<UserBusiness>>().Result;
                return Json(new { status = "true" });
            }
            return Json(new { status = "false" });
        }
    }
}

KingShipper/Areas/Admin/Controllers/UserController.cs
using KingShipper.Library;
using KingShipper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingShipper.Entity;
using KingShipper.Areas.Admin.Models;

namespace KingShipper.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class UserController : Controller
    {
        // GET: Admin/User
        HttpClient client;
        public UserController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        public async Task<ActionResult> Index()
        {
            string url = Config.WebApiUrl + "/api/User/GetAll";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<User>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<User>>().Result;
            }
            return this.View(responseData);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new User();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(User model, FormCollection form)
        {
            model.RoleID = Int16.Parse(form["role"]);
            string url = Config.WebApiUrl + "/api/User/Add";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, model);
            var responseData = new ResponseModel<User>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<User>>().Result;
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }
    }
}

KingShipper/Areas/Admin/Controllers/UserPermissionController.cs
using KingShipper.Library;
using KingShipper.Models;
using Microsoft.Security.Application;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingShipper.Entity;
using KingShipper.Service.Services;
using KingShipper.Areas.Admin.Models;

namespace KingShipper.Areas.Admin.Controllers
{
    public class UserPermissionController : Controller
    {
        HttpClient client;
        public UserPermissionController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }
        // GET: Admin/UserBusiness
        [HttpGet]
        public async Task<ActionResult> Index(int userId)
        {
            string url = Config.WebApiUrl + "/api/UserPermission/GetAll?userId=" + userId;
            Session["UserRoleID"] = userId;
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<UserPermissionModel>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<UserPermissionModel>>().Result;
            }
            return this.View(responseData);
        }

        [HttpPost]
        public async Task<ActionResult> Update(int permissionId)
        {
            int userId = int.Parse(Session["UserRoleID"].ToString());
            var userPermission = UserPermissionService.GetUserPermissionById(userId, permissionId);
            if (userPermission.Status == null || userPermission.Status == 0)
            {
                userPermission.Status = 1;
            }
            else
            {
                userPermission.Status = 0;
            }
            string url = Config.WebApiUrl + "/api/UserPermission/Update";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, userPermission);
            var responseData = new ResponseModel<UserPermission>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<UserPermission>>().Result;
                return Json(new { status = "true" });
            }
            return Json(new { status = "false" });
        }
    }
}

KingShipper/Areas/Admin/Views/User/Add.cshtml
@model KingShipper.Entity.User

@{
    ViewBag.Title = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>User</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Birthday, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Birthday, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        <div style="margin-left:200px">
            <label style="margin-right:60px">Role:</label>
            <select name="role" class="form-group">
                <option value="1">Admin</option>
                <option value="2">Employee</option>
                <option value="3">Customer</option>
            </select>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Updated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Updated, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Updated, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

KingShipper/Areas/Admin/Views/User/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

KingShipper/Areas/Admin/Views/User/Index.cshtml
@model KingShipper.Models.ResponseModel<KingShipper.Entity.User>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="graph-visual tables-main">
    <h2 class="inner-tittle">User Table</h2>
    <div class="graph">
        <div class="tables">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            <a href="@Url.Action("Add")">Add</a>
                        </th>
                    </tr>
                    <tr>
                        <th>STT</th>
                        <th>Name</th>
                        <th>User Name</th>
                        <th>Email</th>
                        <th>Address</th>
                        <th>Birthday</th>
                        <th>Role</th>
                        <th>Status</th>
                        <th>Created</th>
                        <th>Updated</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @{   var i = 1; var roleName = "";}
                    @foreach (var item in Model.DataList)
                    {

                        if(item.RoleID == 1)
                        {
                            roleName = "Admin";
                        }else if(item.RoleID == 2)
                        {
                            roleName = "Employee";
                        }
                        else
                        {
                            roleName = "Customer";
                        }
                        <tr>
                            <th scope="row">@i</th>
                            <td>@item.Name</td>
                            <td>@item.UserName</td>
                            <td>@item.Email</td>
                            <td>@item.Address</td>
                            <td>@item.Birthday</td>
                            <td>@roleName</td>
                            <td>@item.Status</td>
                            <td>@item.Created</td>
                            <td>@item.Updated</td>
                            <td>
                                <a href="@Url.Action("Delete", @item.Id)">Delete | </a>
                                <a href="@Url.Action("Update", @item.Id)">Update | </a>
                                <a href="@Url.Action("Index", "UserBusiness", new { userId = item.Id })">Business</a>
                                <a href="@Url.Action("Index", "UserPermission", new { userId = item.Id })">Permission</a>
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

KingShipper/Areas/Admin/Views/User/Update.cshtml
@{
    ViewBag.Title = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>Update</h2>