KingShipper/Areas/Admin/Controllers/BusinessController.cs
using KingShipper.Areas.Admin.Models;
using KingShipper.Entity;
using KingShipper.Library;
using KingShipper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace KingShipper.Areas.Admin.Controllers
{
    public class BusinessController : Controller
    {

        HttpClient client;
        public BusinessController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }
        // GET: Admin/Business
        public async Task<ActionResult> Index()
        {
            string url = Config.WebApiUrl + "/api/Business/GetAll";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<Business>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<Business>>().Result;
            }
            return this.View(responseData);
        }

        [HttpPost]
        public async Task<ActionResult> Update()
        {
            var reflectionController = new ReflectionController();
            var listController = new List<Type>();
            listController = reflectionController.GetController("KingShipper.Areas.Admin");

            string url = Config.WebApiUrl + "/api/Business/Update";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, listController);

            var responseData = new ResponseModel<Business>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<Business>>().Result;
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

KingShipper/Areas/Admin/Controllers/CategoryController.cs
using KingShipper.Library;
using KingShipper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingShipper.Entity;
using KingShipper.Areas.Admin.Models;

namespace KingShipper.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class CategoryController : Controller
    {
        HttpClient client;
        public CategoryController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        [HttpGet]
        public async Task<ActionResult> Index()
        {
            string url = Config.WebApiUrl + "/api/Category/GetAll";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<Category>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<Category>>().Result;
            }
            return this.View(responseData);
        }

        [HttpGet]
        public ActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }

        [HttpGet]

        public ActionResult Add()
        {
            return View();
        }

    }
}

KingShipper/Areas/Admin/Controllers/UserController.cs
using KingShipper.Library;
using KingShipper.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using KingShipper.Entity;
using KingShipper.Areas.Admin.Models;

namespace KingShipper.Areas.Admin.Controllers
{
    [AuthorizeController]
    public class UserController : Controller
    {
        // GET: Admin/User
        HttpClient client;
        public UserController()
        {
            client = new HttpClient();
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        public async Task<ActionResult> Index()
        {
            string url = Config.WebApiUrl + "/api/User/GetAll";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.GetAsync(url);
            var responseData = new ResponseModel<User>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<User>>().Result;
            }
            return this.View(responseData);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var model = new User();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add(User model, FormCollection form)
        {
            model.RoleID = Int16.Parse(form["role"]);
            string url = Config.WebApiUrl + "/api/User/Add";
            client.BaseAddress = new Uri(url);
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(url, model);
            var responseData = new ResponseModel<User>();
            if (responseMessage.IsSuccessStatusCode)
            {
                responseData = responseMessage.Content.ReadAsAsync<ResponseModel<User>>().Result;
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Update()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Delete()
        {
            return View();
        }
    }
}

KingShipper/Areas/Admin/Views/Shared/_Fotter.cshtml
     <!--footer section start-->
<footer>
    <p>&copy 2016 Augment . All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">W3layouts.</a></p>
</footer>
<!--footer section end-->
      </div>
        </div>
<!--//content-inner-->
    </div>
<script>
    var toggle = true;

    $(".sidebar-icon").click(function () {
        if (toggle) {
            $(".page-container").addClass("sidebar-collapsed").removeClass("sidebar-collapsed-back");
            $("#menu span").css({ "position": "absolute" });
        }
        else {
            $(".page-container").removeClass("sidebar-collapsed").addClass("sidebar-collapsed-back");
            setTimeout(function () {
                $("#menu span").css({ "position": "relative" });
            }, 400);
        }

        toggle = !toggle;
    });
</script>
<!--js -->
<link rel="stylesheet" href="~/Areas/Admin/css/vroom.css">
<script type="text/javascript" src="~/Areas/Admin/js/vroom.js"></script>
<script type="text/javascript" src="~/Areas/Admin/js/TweenLite.min.js"></script>
<script type="text/javascript" src="~/Areas/Admin/js/CSSPlugin.min.js"></script>
<script src="~/Areas/Admin/js/jquery.nicescroll.js"></script>
<script src="~/Areas/Admin/js/scripts.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="~/Areas/Admin/js/bootstrap.min.js"></script>

</body>
</html>

KingShipper/Areas/Admin/Views/Shared/_Layout.cshtml
@Html.Partial("~/Areas/Admin/Views/Shared/_Header.cshtml")
<div>
    @RenderBody()

    <hr />
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
@Html.Partial("~/Areas/Admin/Views/Shared/_Fotter.cshtml")
@Html.Partial("~/Areas/Admin/Views/Shared/_Sidebar.cshtml")





               
       
       
      

KingShipper/Areas/Admin/Views/Shared/_Sidebar.cshtml
 <!--/sidebar-menu-->
@{
    var role = Session["Role"].ToString();
    if(role.Equals("2"))
    {
        role = "employee";
    }
}
<div class="sidebar-menu">
    <header class="logo">
        <a href="#" class="sidebar-icon"> <span class="fa fa-bars"></span> </a> <a href="index.html">
            <span id="logo"> <h1>Product Management</h1></span>
            <!--<img id="logo" src="" alt="Logo"/>-->
        </a>
    </header>
    <div style="border-top:1px solid rgba(69, 74, 84, 0.7)"></div>
    <!--/down-->
    <div class="down">
        <a href="index.html"><img src="images/admin.jpg"></a>
        <a href="index.html"><span class=" name-caret">@Session["UserName"].ToString()</span></a>
        <p>System Administrator in Company</p>
        <ul>
            <li><a class="tooltips" href="index.html"><span>Profile</span><i class="lnr lnr-user"></i></a></li>
            <li><a class="tooltips" href="index.html"><span>Settings</span><i class="lnr lnr-cog"></i></a></li>
            <li><a class="tooltips" href="@Url.Action("Login","Account")"><span>Log out</span><i class="lnr lnr-power-switch"></i></a></li>
        </ul>
    </div>
    <!--//down-->
    <div class="menu">
        <ul id="menu">
            <li><a href="index.html"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
            <li id="menu-academico">
                <a href="#"><i class="fa fa-table"></i> <span> Tabs &amp; Panels</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                <ul id="menu-academico-sub">
                    <li id="menu-academico-avaliacoes"><a href="tabs.html"> Tabs &amp; Panels</a></li>
                    <li id="menu-academico-boletim"><a href="widget.html">Widgets</a></li>
                    <li id="menu-academico-avaliacoes"><a href="calender.html">Calendar</a></li>

                </ul>
            </li>
            <li id="menu-academico" class="@role">
                <a href="#"><i class="fa fa-file-text-o"></i> <span>Quản lý người dùng</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                <ul id="menu-academico-sub">
                    <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index", "User")">Danh sách người dùng</a></li>
                    <li id="menu-academico-boletim"><a href="@Url.Action("Index", "Customer")">Khách hàng</a></li>

                </ul>
            </li>

            <li class="@role"><a href="@Url.Action("Index", "Business")"><i class="fa fa-file-text-o"></i>Danh sách nghiệp vụ</a></li>

            <li id="menu-academico">
                <a href="#"><i class="fa fa-file-text-o"></i> <span>Quản lý sản phẩm</span> <span class="fa fa-angle-right" style="float: right"></span></a>
                <ul id="menu-academico-sub">
                    <li id="menu-academico-avaliacoes"><a href="@Url.Action("Index", "Category")">Loại sản phẩm</a></li>
                    <li id="menu-academico-boletim"><a href="@Url.Action("Index", "Product")">Sản phẩm</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

<div class="clearfix"></div>
<script>
    $(document).ready(function () {
        $(".employee").hide();
    })
</script>
      